// main.dart

import 'package:flutter/material.dart';
import 'package:camera/camera.dart';
// Removed: import 'package:firebase_core/firebase_core.dart';
// Removed: import 'package:firebase_auth/firebase_auth.dart';
import 'dashboard_page.dart';
import '../detection/detection_service.dart';
// Removed: import 'login_page.dart';
// Removed: import 'firebase_options.dart'; // Generated by FlutterFire CLI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Removed Firebase Initialization:
  // await Firebase.initializeApp(
  //   options: DefaultFirebaseOptions.currentPlatform,
  // );

  // Get available cameras
  final cameras = await availableCameras();

  runApp(MyApp(cameras: cameras));
}

class MyApp extends StatelessWidget {
  final List<CameraDescription> cameras;
  const MyApp({super.key, required this.cameras});

  @override
  Widget build(BuildContext context) {
    // Labels for your detection model
    final detectionLabels = ['cattle']; 

    final detectionService = DetectionService(labels: detectionLabels);

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Cattle Detection App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      // App now goes directly to the Dashboard, assuming no login is needed.
      home: DashboardPage(
        cameras: cameras,
        detectionService: detectionService,
      ),
    );
  }
}

// Removed AuthWrapper:
// /// AuthWrapper decides which page to show based on Firebase login status
// class AuthWrapper extends StatelessWidget {
//   final List<CameraDescription> cameras;
//   final DetectionService detectionService;

//   const AuthWrapper({
//     super.key,
//     required this.cameras,
//     required this.detectionService,
//   });

//   @override
//   Widget build(BuildContext context) {
//     return StreamBuilder<User?>(
//       stream: FirebaseAuth.instance.authStateChanges(),
//       builder: (context, snapshot) {
//         if (snapshot.connectionState == ConnectionState.waiting) {
//           return const Scaffold(
//             body: Center(child: CircularProgressIndicator()),
//           );
//         } else if (snapshot.hasData) {
//           return DashboardPage(
//             cameras: cameras,
//             detectionService: detectionService,
//           );
//         } else {
//           return const LoginPage();
//         }
//       },
//     );
//   }
// }